<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\EidolonCore\EidolonCore.csproj" />
      <ProjectReference Include="..\Vulkan\Vulkan.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Include="bin\Debug\net10.0\Rendering\Shaders\basic.frag" />
      <None Include="bin\Debug\net10.0\Rendering\Shaders\basic.frag.spv" />
      <None Include="bin\Debug\net10.0\Rendering\Shaders\basic.vert" />
      <None Include="bin\Debug\net10.0\Rendering\Shaders\basic.vert.spv" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="bin\Debug\net10.0\" />
    </ItemGroup>

</Project>
